//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoDealers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Autos_BuyersID
    {
        public int Autos_BuyersID1 { get; set; }
        public Nullable<int> AutoID { get; set; }
        public Nullable<int> BuyerID { get; set; }
    
        public virtual Auto Auto { get; set; }
        public virtual Auto Auto1 { get; set; }
        public virtual Autos_BuyersID Autos_BuyersID11 { get; set; }
        public virtual Autos_BuyersID Autos_BuyersID2 { get; set; }
        public virtual Buyer Buyer { get; set; }
    }
}
