//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoDealers.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AutoDealerEntities : DbContext
    {
        public AutoDealerEntities()
            : base("name=AutoDealerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Auto> Autos { get; set; }
        public virtual DbSet<Autos_BuyersID> Autos_BuyersID { get; set; }
        public virtual DbSet<Buyer> Buyers { get; set; }
    }
}
